name: 'STAGE_NESTING_TEST_$(Date:yyyyMMdd).$(Rev:rrr)'

pr: none

trigger: none

pool:
  name: Default

variables:
  - group: Versioning


stages:

  - stage: 'BumpVersion'
    displayName: 'Bump Version'
    jobs:
      - job:
        steps:
          - bash: |
              CurrentStaging=$(NextStagingVersion)
              CurrentStagingSplit=( ${CurrentStaging//./ } )
              NewStagingVersion=${CurrentStagingSplit[0]}.${CurrentStagingSplit[1]}.$((CurrentStagingSplit[2]+1))
              echo "##vso[task.setvariable variable=NewStagingVersion;]$NewStagingVersion"
            displayName: 'Calculate new version'
            continueOnError: False
          - template: './templates/set-variable.template.yml'
            parameters:
              job:
                displayName: 'Set next Staging version'
              variableGroup:
                prodBranch: $(ProdBranch)
                nextProdVersion: $(NextProdVersion)
                stagingBranch: $(StagingBranch)
                nextStagingVersion: $(NewStagingVersion)

  - stage: 'NewStagingBranch'
    displayName: 'New Staging Branch'
    dependsOn:
      - BumpVersion
    jobs:
      - job:
        steps:
          - bash: |
              echo '$(NextProdVersion)'
              echo '$(NextStagingVersion)'
              echo '$(ProdBranch)'
              echo '$(StagingBranch)'
            displayName: 'Print versions'
            continueOnError: False
          - bash: |
              CurrentStaging=$(NextStagingVersion)
              CurrentStagingSplit=( ${CurrentStaging//./ } )
              NewStagingVersion=${CurrentStagingSplit[0]}.$((CurrentStagingSplit[1]+1)).0
              NewStagingBranch=v${CurrentStagingSplit[0]}.$((CurrentStagingSplit[1]+1)).x
              echo "##vso[task.setvariable variable=NewStagingVersion;]$NewStagingVersion"
              echo "##vso[task.setvariable variable=NewStagingBranch;]$NewStagingBranch"
            displayName: 'Calculate new version'
            continueOnError: False
          - checkout: self
            clean: True
            persistCredentials: True
          - bash: |
              set -e
              git fetch --unshallow
              git checkout develop
              git pull
              git checkout -b release/$(NewStagingBranch)
              git push origin release/$(NewStagingBranch)
            displayName: 'Create staging branch'
            continueOnError: False
          - template: './templates/set-variable.template.yml'
            parameters:
              job:
                displayName: 'Set variables for new staging branch'
              variableGroup:
                prodBranch: $(StagingBranch)
                nextProdVersion: $(NextStagingVersion)
                stagingBranch: $(NewStagingBranch)
                nextStagingVersion: $(NewStagingVersion)
