parameters:
  something:
    shouldBeTrue: True
    shouldBeFalse: False

stages:
  - stage: "Build"
    displayName: "Build the thing"
    jobs:
      - job:
        condition: eq(${{ parameters.something.shouldBeTrue }}, True)
        steps:
          - bash: |
              echo "Building..."   
