parameters:
  shouldBeTrue: True
  shouldBeFalse: False
  something:
    shouldBeTrue: True
    shouldBeFalse: False
  nothing:
    shouldBeTrue: True
    shouldBeFalse: False

stages:
  - stage: "Build"
    displayName: "Build the thing"
    jobs:
      - job:
        condition: eq(${{ parameters.shouldBeTrue }}, True)
        steps:
          - bash: |
              echo "${{ parameters.shouldBeTrue }}"
              echo "Building..."   
