stages:
  - stage: "PostDeploy"
    displayName: "Deploy Jobs"
    dependsOn:
      - DeployApi
      - DeployJobs
    jobs:
      - job:
        steps:
          - template: 'CoLoBugger.template.yml'
